### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by maxarteev** [dodorare/crossbow#156]
## Crossbow version

crossbow 0.2.2

## What you did

create apk with "crossbundle build android -s=native-apk"

## What went wrong

- error in screenshot

## Additional information

Hi! 
This is my problem on Android 
![photo_2022-09-12_13-07-00](https://user-images.githubusercontent.com/11098085/189628970-942c98dd-5431-4308-8469-60b476004380.jpg)
I use "bevy" template and "aarch64-linux-android" architecture on windows
Folder and library isset in .apk
![2022-09-12_13-13-37](https://user-images.githubusercontent.com/11098085/189629534-a837ae7c-ad2d-470e-9240-2cf15c715a7d.jpg)

What am I doing wrong ?

**Comment by enfipy** [comment]
I'm pretty sure it's because of audio dependencies. Can you try to remove some features from bevy and make it like this:

```
bevy = { version = "0.8.1", default-features = false, features = ["bevy_winit", "render", "bevy_asset"] }
```

And with bevy patch that in crossbow root `Cargo.toml`. Because bevy has different ndk-glue versions and will fail otherwise.

**Comment by maxarteev** [comment]
Yes, it works, thank you so much =)

**Comment by enfipy** [comment]
Glad to hear this! I also hope we will merge ndk-glue patch to bevy real soon ;)
