### ISSUE TITLE
Problems with compilation crossbundle

### ISSUE THREAD

**Issue by KamilM1205** [dodorare/crossbow#55]
When I'm trying to compile crossbundle, I'm catching error.

error: cannot find derive macro \`Parser\` in this scope
  --> crossbundle/cli/src/commands/build/android.rs:15:10
   |
15 | #[derive(Parser, Clone, Debug)]
   |          ^^^^^^
   |
note: \`Parser\` is imported here, but it is only a trait, without a derive macro
  --> crossbundle/cli/src/commands/build/android.rs:4:5
   |
4  | use clap::Parser;
   |     ^^^^^^^^^^^^

**Comment by KamilM1205** [comment]
I fixed it by editing crossbandle/cli/Cargo.toml. I changed `clap = "3.0.0-beta.5"` to `clap = {version = "3.0.0-beta.5", features = [ "derive" ] }`

**Comment by enfipy** [comment]
Closing as `clap` minor version released, and we moved to it.
