### ISSUE TITLE
use_android_manfiest and android_manifest_path are ignored?

### ISSUE THREAD

**Issue by beling** [dodorare/crossbow#70]
I cannot force crossbundle to use my android manifest file (under linux).
In my `Cargo.toml` in `[package.metadata]` I have:
`use_android_manfiest = true`
and I have tried both without `android_manifest_path` (and manifest in the same directory as `Cargo.toml`) and with `android_manifest_path` (giving the path in many different ways).
Each time crossbundle puts in apk the manifest generated by itself.

**Comment by enfipy** [comment]
Crossbundle automatically parses `AndroidManifest.xml` specified by `android_manifest_path` and saves it in `target/android/<profile>/AndroidManifest.xml` file. Then apk generated and puts it inside the final `.apk` file as binary xml. You can play with `macroquad-3d` example and see that `res/AndroidManifest.xml` actually used (we added it in a recent change).
