### ISSUE TITLE
Replace CargoManifest from cargo_toml to TomlManifest from cargo

### ISSUE THREAD

**Issue by enfipy** [dodorare/crossbow#73]
Replace `CargoManifest` from `cargo_toml` crate to `TomlManifest` from `cargo` crate.

Remove `cargo_toml` crate from dependencies.

https://docs.rs/cargo/latest/cargo/util/toml/struct.TomlManifest.html

**Comment by Heezay** [comment]
#79 Added pull request to merge changes. Was replaced CargoManifest to TomlManifest, so cargo_toml was removed from cargo.toml.
